apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: site
      defaultBucket: stroomdata
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
