listener 1883
protocol mqtt

# Websockets, handig als je ooit een browser-dashboard rechtstreeks op MQTT wil laten meelezen
listener 9001
protocol websockets

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Dit netwerk draait geïsoleerd op het festivalterrein achter de Unifi-switches.
# allow_anonymous true is daarom acceptabel voor de eerste opzet, maar zet dit uit
# zodra je met een wachtwoordbestand werkt (mosquitto_passwd), zeker als er ooit
# een uplink naar het publieke internet bij komt.
allow_anonymous true
